import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <nav className="fixed top-0 h-20 shadow w-full flex items-center justify-center gap-8">
          <Link href="/number1to2">
            <div className="cursor-pointer hover:underline">
              Soal No.1 s/d no.2
            </div>
          </Link>
          <Link href="/number3to6">
            <div className="cursor-pointer hover:underline">
              Soal No.3 s/d no.6
            </div>
          </Link>
          <Link href="/number7">
            <div className="cursor-pointer hover:underline">Soal No.7</div>
          </Link>
          <Link href="/">
            <div className="cursor-pointer hover:underline">Soal No.9</div>
          </Link>
        </nav>
        <main className="w-full h-full min-h-screen mx-auto px-8 pt-20 flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
